package com.parking.util;
/**
 *     枚举公共类
 * @see 	 
 */


public enum CommEnum {
	
	APP_CODE("eparking","000000"), //应用编码
	RES_TYPE_AUTO_CARD_PAY("AutoCardPay","月卡自动扣费"),
	RES_TYPE_CARD_PAY("CardPay","月卡手动缴费"),
	RES_TYPE_AUTO_PAY("AutoPay","业务类型，无感支付"),
	PAY_CODE("1","渠道支付开启"),
	PAY_TAG("1","支付标志，收银台支付时渠道区分"),
	GZBD_CHANNEL_00("00","自身多渠道支付类型"),
	CMB_CHANNEL("18","招行后台支付渠道"),
	CARD_ID_62("62**","默认62值用于收银台支付时标志，代表无感支付"),
	ORDER_GENE_EXCEPTION_DESC("error","生成此笔订单流水异常了或者重复下单异常"),
	ORDER_PRIOITY("100","置默认值值"),
	TOKEN_VALUE("L0X00","支付时默认置"),
	TRADE_FAIL_DESC("980002","交易失败"),
	MCHNT_EQUIT_ID_0("0","权益商户号为0时"),
	TRADE_RISK_AMOUNT_DESC("999905","此笔交易,交易金额异常"),
	TRADE_RISK_CAR_STATES_DESC("980002","此车牌未开启无感支付或暂不可支付"),
	PR_AGEN_CMB_SERVCIE("agentCmbPay","招行一网通系统支付"),
	PR_CHISHE_PAY_ORDER_A_SERVICE("payOrderA","收银台系统支付"),
	SELF_STOP_CAR("00","自助停车["),
	CARD_SELF_STOP_CAR("00","月卡缴费["),
	BRACKET_LIFT("[","左中括号"),
	BRACKET_RIGHT("]","右中括号"),
    NO_PARKG_MCHNT_CONF_DESC("","此停车场未配置渠道商户不可支付["),
	FREE0_CODE("0","交易金额为0"),
	FREE00_CODE("00","交易金额为00"),
	FREE000_CODE("000","交易金额异常"),
	PARKING_TIME_FEE("timeFee","按此收费"),
	CARD_TYPE_CODE_N("N","非月卡"),
	FLAG_CODE("1","unicode编码"),
	FLAG_CODE0("0","UTF-8编码"),
    EPARKING_PARAMS("params=","车易泊请求参数"),
	PAY_ORDER_CREATED("Created","订单初始初始状态"),
	PAY_PAID_CODE("Paid","支付成功"),
	PAY_Finished_CODE("Finished","销账成功"),
	PAY_PAYFILE_CODE("PayFail","支付失败"),
	PAY_PAYING_CODE("Paying","支付中"),
	PAY_Accounting_CODE("Accounting","销账异常"),
	PAY_CLOSED_CODE("Closed","订单关闭"),
	PAY_UN_PAID("Unpaid","待支付"),
	REFUNDING("Refunding","退款中"),
	REFUNDED_FAIL("RefundedFail","退款失败"),
	REFUNDED("Refunded","退款成功"),
	CONSUMEUN("ConsumeUn","消费已撤销"),
	FLAG_TOKEN("1","需token验证"),
	FLAG_TOKEN0("0","不需token验证"),
    HOUES_CODE("houes","时"),
    MINUTS_CODE("minuts","分"),
    SECOND_CODE("second","秒"),
    TIME_LONG("timeLong","时长"),
    UNIONAPY_CODE("Unionpay","银联二维码类型"),
    WECHAT_CODE("weChat","微信二维码类型"),
    ALIPAY_CODE("alipay","支付宝二维码类型"),
    GZBDPAY_CODE("gzbdPay","博大渠道"),
    YNNXAPY_CODE("ynnxPay","农信渠道"),
    CCBPAY_CODE("ccbPay","建设银行龙支付渠道"),
    CEBPAY_CODE("cebPay","光大银行支付渠道"),
    MIS_POSTPAY_CODE("yshPosPay","银商pos通被扫"),
    HMFPAY_CODE("hippoPay","河马付渠道"),
    FDPAY_CODE("fudianPay","富滇银行支付渠道"),
    CIB_CODE("cibPay","兴业银行支付渠道"),
    CNCB_CODE("cncbPay","中信银行支付渠道"),
    SH_CCBPAY_CODE("shccbPay","上海众合 建设银行渠道"),
    ALLINPAY_CODE("allinPay","通联支付渠道"),
    SW_UNION_PAY_CODE("swunionPay","Sw中国银联 渠道条码前置"),
    CMBCPAY_CODE("cmbcPay","民生银行支付渠道"),
    BOCPAY_CODE("bocPay","四川中行支付渠道"),
    XJ_BOCPAY_CODE("xjBocPay","新疆中行支付渠道"),
    TRAVEL_YN_PAY_CODE("travelynPay","游云南 渠道"),
    ICBCPAY_CODE("icbcPay","中国工商银行 主扫支付渠道"),
    BESTPAY_CODE("bestPay","翼支付渠道"),
    HXBPAY_CODE("hxbPay","华夏银行支付渠道"),
    BCMPAY_CODE("bcmPay","交通银行 智慧行 被扫付款"),
    COMM_BE_CODE_UTIL("commPay","停车场公共渠道被扫，内部业务划分使用"),
    CCB_Y("Y","成功"),
    CCB_N("N","失败"),
    CCB_U("U","此订单支付不确定"),
    CCB_Q("Q","此订单支付待查询"),
    RES_ID("0000000","默认车牌值"),
    PERMIN_CHECK_CODE("0","无权限"),
    MCHNT_NAME_23("23","银联金融事业部智慧平台"),
    UNIONPAY_SH_CHANNEL("23","上海金融智慧事业部平台"),
    CCB_PAY_CHANNEL("22","建设银行龙支付平台，无感支付"),
    MCHNT_NAME_22("22","建设银行渠道"),
    CMB_PAY_CHANNEL("24","招行银行平台，无感支付"),
    MCHNT_NAME_24("24","招商银行渠道"),
    BOC_PAY_CHANNEL("25","中行银行平台，无感支付"),
    CIB_PAY_CHANNEL("26","兴业银行平台，无感支付"),
    ICBC_PAY_CHANNEL("27","工商银行平台，无感支付"),
    SZ_PAY_CHANNEL("28","深圳银联渠道平台，无感支付"),
    CENTIRY_DIS_CHANNEL("29","世纪恒通优惠全部抵扣时出现"),
    TRAVELYN_PAY_CHANNEL("31","一部手机游云南,无感支付"),
    ZYCB_PAY_CHANNEL("32","贵州银行平台,无感支付"),
    ALI_PAY_CHANNEL("33","支付宝平台,无感支付"),
    MCHNT_NAME_25("25","博众-停车场"),
    MCHNT_NAME_26("26","兴业银行渠道"),
    MCHNT_NAME_27("27","工商银行渠道"),
    MCHNT_NAME_28("28","深圳银联渠道"),
    MCHNT_NAME_29("29","世纪恒通渠道"),
    MCHNT_NAME_31("31","游云南渠道"),
    MCHNT_NAME_32("32","贵州银行"),
    MCHNT_NAME_33("33","支付宝渠道"),
    EPARKING_RESP_DATA("data","车易泊返回json实体数据"),
    EPARKING_RESP_CODE("code","车易泊返回json返回码"),
    EPARKING_RESP_INFO("info","车易泊返回json返回描述"),
    UNIONPAY_SH_RESULT_CODE_0("0","智慧平台成功返回码"),
    UNIONPAY_SH_RESULT_CODE_1001("1001","必选参数为空"),
    UNIONPAY_SH_RESULT_CODE_1002("1002","参数格式错误，具体字段提示"),
    UNIONPAY_SH_RESULT_CODE_1003("1003","系统错误"),
    UNIONPAY_SH_RESULT_CODE_1004("1004","签名失败"),
    UNIONPAY_SH_RESULT_CODE_1005("1005","授权失败"),
    UNIONPAY_SH_RESULT_CODE_1006("1006","IP 不在白名单内"),
    UNIONPAY_SH_RESULT_CODE_1007("1007","车辆不在场内"),
    UNIONPAY_SH_PAY_STATUS_0("0","支付成功"),
    UNIONPAY_SH_PAY_STATUS_1("1","支付中"),
    UNIONPAY_SH_PAY_STATUS_2("2","支付失败"),
    UNIONPAY_SH_PAY_STATUS_3("3","退款中"),
    UNIONPAY_SH_PAY_STATUS_4("4","退款成功"),
    UNIONPAY_SH_PAY_STATUS_5("5","退款失败"),
    UNIONPAY_SH_ENTER_INSUCCESS("InSucceed(UnionpaySh)","入场通知成功"),
    UNIONPAY_SH_ENTER_INFAILL("InFailure(UnionpaySh)","入场通知失败"),
    UNIONPAY_SH_OUTSUCCESS("OutSuccess(UnionpaySh)","出场通知成功"),
    UNIONPAY_SH_OUTFAIL("OutFail(UnionpaySh)","出场通知失败"),
    UNIONPAY_SH_GET_PAY_STATUS("shGetPayStatus","智慧平台查询支付订单状态接口"),
    UNIONPAY_SH_REFUND_BILL("shPushRefundBill","智慧平台退款服务"),
    UNIONPAY_SH_GET_REFUND_STATUS("shGetRefundStatus","智慧平台查询退款状态"),
    UNIPNPAY_SH_PUSH_PAY_BILL("shPushPayBill","智慧平台下支付订单"),
    UNIONPAY_SH_PUSH_NOTICE_EXIT("shPushNoticeExit","智慧平台出场通知"),
    UNIONPAY_SH_PUSH_NOTICE_ETRANCE("shPushNoticeEntrance","智慧平台入场通知"),
    UNIONPAY_NUMBER_PARAMS_ID("number","停车id参数名称"),
    UNIONPAY_CAR_PLATE_PARAMS("carPlate","停车车牌参数名称"),
    UNIONPAY_ENTER_INSUCCESS("InSucceed(Unionpay)","入场通知成功"),
    UNIONPAY_ENTER_INFAILL("InFailure(Unionpay)","入场通知失败"),
    UNIONPAY_OUTSUCCESS("OutSuccess(Unionpay)","出场通知成功"),
    UNIONPAY_OUTFAIL("OutFailure(Unionpay)","出场通知失败"),
    GET_MSG_TAG("tag","内部Map标示"),
    TAG_SUECCESS("1","成功标示"),
    TAG_FAIL("0","失败标示"),
    XML_RESP_MSG_KEY("msg","内部xml返回根节点msg信息"),
    RESP_CODE("respCode","返回码"),
    RESP_DESC("respDesc","返回描述"),
    PR_PARKING_UIONPAY_SERVICE("PrParkingUnionPayService","接入渠道智慧平台服务调用系统名称"),
    CALL_SYNC("sync","dubbo调用同步标示"),
    CALL_ASYN("asyn","dubbo调用异步标示"),
    IN_TIME("inTime","入场时间属性"),
    OUT_TIME("outTime","出场时间属性"),
    ACC_SPLIT_TYPE("accSplitType","银联智慧平台分账类型"),
    ACC_SPLIT_RULE_ID("accSplitRuleId","银联智慧平台分账规则id"),
    REQ_PARAMS_IS_NULL("-1","此业务参数缺失"),
    IS_SUCCESS("SUCCESS","请求成功头返回标示，返回两端报文时返回"),
    RESP_DESC_ERROR("999916","其他错误"),
    TRADE_STAT_OK("OK","xml报文请求头成功时返回"),
    SYS_PARKING_NAME("parking","本地应用系统名称"),
    PR_CCB_PAY_SERVICE("PrCcbPayService","接入建设银行渠道无感支付渠道服务名称"),
    CCB_PAY_GET_NO_SENSE_TRADE_QUERY("getNoSenseTradeQuery","接入建设银行渠道无感车牌查询接口"),
    CCB_PAY_GET_NO_SENSE_TRADE_PAY("getNoSenseTradePay","接入建设银行渠道无感支付接口"),
    CCB_STATUS_0("0","未开通无感支付"),
    CCB_STATUS_1("1","已开通无感支付"),
    CMB_STATUS_1("1","渠道配置参数状态"),
    GZBD_DB_STATUS("1","通用DB状态参数1:开启"),
    UN_PERMIT_STATUS_00("00","已开通无感支付"),
    UN_PERMIT_STATUS_01("01","未开通无感支付"),
    UN_PERMIT_STATUS_02("02","其他状态"),
    CCB_QUERY_STATUS_TXCODE("WGZF01","查询无感状态预查询交易码"),
    CCB_PAY_TXCODE("WGZF00","建行无感支付交易码"),
    UNIONPAY_GZBD_SH_MCHNT_ID("800085100100007","智慧平台使用自定义预交费商户号"),
    CMB_PAY_GZBD_MCHNT_ID("800085100100009","招行渠道平台使用自定义预缴费商户号"),
    BOC_PAY_GZBD_MCHNT_ID("800085100100010","中行渠道平台使用自定义缴费商户号"),
    CIB_PAY_GZBD_MCHNT_ID("800085100100011","兴业银行渠道平台使用自定义缴费商户号"),
    ICBC_PAY_GZBD_MCHNT_ID("800085100100012","工商银行渠道平台使用自定义缴费商户号"),
    SJHT_PAY_GZBD_MCHNT_ID("800085100100013","世纪恒通渠道平台使用自定义缴费商户号"),
    SZ_UIONPAY_PAY_GZBD_MCHNT_ID("800085100100014","深圳银联渠道平台使用自定义缴费商户号"),
    ZYCB_PAY_GZBD_MCHNT_ID("800085100100015","贵州银行渠道平台使用自定义缴费商户号"),
    SYS_CLOUD("cloud","停车场cloud系统平台名称"),
    SYNCINFO_NOTIFY_MONITORING_RESULT("notifyMonitoringResult","通知监控系统服务名称"),
    ATTACH_GET_USER_INFO("UserInfo","获取用户信息服务名称"),
    CORE_TRANS_SERVICE("CoreTransService","核心交易系统名称"),
    UNION_PAY_TRADE_PUSH_SERVICE("tradeIdPush","贵州云闪付支付下单接口"),
    PARKING_SON_SERVICE("ParkingSonService","停车场子系统名称"),
    PARKING_CCBECODE_PAY_SERVICE("ccbenpay","建行被扫下单接口"),
    CCB_QUERY_RESULT_SERVICE("ccbqueryresult","建行轮询支付结果接口"),
    CCB_ACTIVE_QUERY_RESULT_SERVICE("ccbactivequeryresult","建行订单支付状态查询"),
    PR_CCBE_CODE_SERVCIE("CcbBeCodeService","建行系统名称"),
    QR_EFFECT_TIMES("0","查询初始次数为0"),
    DATE_YYYY_MM_DD_HH_MM_SS("yyyy-MM-dd HH:mm:ss","时间类型格式化年月日时分秒"),
    DATE_YYYYMMDDHHMMSSSSS("yyyyMMddHHmmssSSS","时间类型格式化年月日时分秒毫秒"),
    DATE_YYYYMMDDHHMMSS("yyyyMMddHHmmss","时间类型格式化年月日时分秒"),
    TRADE_ORDER_STATE("1","订单初始状态"),
    SIGN_RSA_METHOD("RSA","RSA加密方式,也是加密方式"),
    PARKING_CEB_SWIFT_ORDER_PAYS_SERVICE("CEBSwiftOrderPays","光大银行被扫下单接口"),
    PARKING_CEB_SWIFT_QUERY_ORDERS_SERVICE("CEBSwiftQueryOrders","光大银行被扫下单状态查询接口"),
    PARKING_CEB_SWIFT_REVOCATION_ORDERS_SERVICE("CEBSwiftRevocationOrders","光大银行渠道被扫撤销交易接口"),
    PARKING_CEB_SWIFT_REFUND_ORDER_PAYS_SERVICE("CEBSwiftRefundOrderPays","光大银行渠道被扫申请退款接口"),
    PARKING_CEB_SWIFT_QUERY_REFUND_ORDERS_SERVICE("CEBSwiftQueryRefundOrders","光大银行渠道查询订单退款接口"),
    PR_CEB_BECODE_SERVICE("PrCebBeCodeService","光大接入系统调用系统名称"),
    CEB_BECODE_PAY_STATUS_0("0","光大银行渠道响应成功，不代表支付成功"),
    CEB_BECODE_PAY_PAY_RESUTLT("0","光大银行渠道支付成功"),
    CEB_BECODE_PAY_TRADE_STATUS_SUCCESS("SUCCESS","光大银行渠道支付"),
    CEB_BECODE_PAY_TRADE_STATUS_REFUND("REFUND","光大银行渠道已退款"),
    CEB_BECODE_PAY_TRADE_STATUS_NOTPAY("NOTPAY","未支付"),
    CEB_BECODE_PAY_TRADE_STATUS_CLOSED("CLOSED","订单已关闭"),
    CEB_BECODE_PAY_TRADE_STATUS_REVOKED("REVOKED","已撤销"),
    CEB_BECODE_PAY_TRADE_STATUS_REVERSE("REVERSE","已撤销"),
    CEB_BECODE_PAY_TRADE_STATUS_USERPAYING("USERPAYING","用户支付中"),
    CEB_BECODE_PAY_TRADE_STATUS_PAYERROR("PAYERROR","支付失败(其他原因，如银行返回失败)"),
    PARKING_ORDER_NAME("00","停车场支付"),
    CHANNEL_MCHNT_NAME_BE_PAY_ALIPAY("alipay","支付宝支付被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_WECHAT("weChat","微信支付被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_UNIONPAY("Unionpay","银联支付被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_YNNXUIONPAYPAY("ynnxUnionPay","云南农信银联线路2被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_YNNXPAY("ynnxPay","云南农信 被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_CCBPAY("ccbPay","建设银行 被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_CEBPAY("cebPay","光大银行 被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_MIS_PSTPAY("yshPosPay","银商pos通 被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_FuDian("fudianPay","富滇银行 被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_CIBPAY("cibPay","兴业银行 被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_Hiipo("hippoPay","河马付 被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_CNCBPAY("cncbPay","中信银行 被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_ShCcbPAY("shccbPay","上海众合建设银行 被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_ALLINPAY("allinPay", "通联支付被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_SwUnionPay("swunionPay","Sw中国银联 被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_CMBCPAY("cmbcPay", "民生支付被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_BOCPAY("bocPay", "四川中行支付被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_TravelYnPay("travelynPay","游云南 被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_XJ_BOCPAY("xjBocPay", "新疆中行支付被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_IcbcPay("icbcPay", "中国工商银行支付被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_BESTPAY("bestPay", "翼支付被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_HXBPAY("hxbPay", "华夏银行支付被扫渠道"),
    CHANNEL_MCHNT_NAME_BE_PAY_BcmPay("bcmPay", "交通银行智慧行"),
    GZBD_ORDER_CURR_STATE_0("0","订单预定义初始状态"),
    GZBD_ORDER_CURR_STATE_1("1","订单初始状态"),
    GZBD_ORDER_CURR_STATE_2("2","交易主表记录会出现，订单销账失败"),
    GZBD_ORDER_CURR_STATE_3("3","支付成功状态"),
    GZBD_ORDER_CURR_STATE_5("5","失败"),
    GZBD_ORDER_CURR_STAT_14("14","需查询状态"),
    GZBD_ORDER_CURR_STATE_6("6","已退款"),
    GZBD_ORDER_CURR_STATE_7("7","退款失败"),
    GZBD_ORDER_CURR_STATE_8("8","退款处理中或申请中"),
    GZBD_ORDER_CURR_STATE_11("11","消费撤销申请中"),
    GZBD_ORDER_CURR_STATE_12("12","消费撤销成功"),
    GZBD_ORDER_CURR_STATE_13("13","消费撤销失败"),
    GZBD_ORDER_CURR_STATE_15("15","交易主表记录里会出现，预缴费订单支付通知恒通时失败会出现"),
    ORDER_BE_OVER_TIME("60","订单超时时间默认值,被扫码适用"),
    PARKING_YUNNPAY_QUERY_ORDER_BY_POST_SERVICE("queryOrderByPOST","云南农信查询接口"),
    PR_YX_BECODE_SERVICE("YxBeCodeService","云南农信被扫系统服务名"),
    SYS_CALL_ERROR_EXCEPTION("exption","系统调用异常"),
    SYS_CALL_PAREEX_EXCEPTION("pareEx","系统调用解析异常"),
    STRING_SPLIT("\\|","字符分割符"),
    PARKING_QRCODE_QUERY_TRADE_SERVICE("queryTrade","博众渠道查询交易服务"),
    CCB_BE_QUERY_QY_TIME("1","建设银行渠道次数固定一次"),
    SUCCESS_COID("000000","成功响应标示"),
    LONG_STRING("|","打印日志内容分割"),
    FAIL_SPLIT("|","错误报文分割划分"),
    CODE_SPLIT("|","业务代码分割组合"),
    MCHNT_C("C","博众渠道专用"),
    CALL_PROXY_ERROR("999910","调用代理异常"),
    CALL_CHANNEL_ERROR("999910","调用渠道异常"),
    PARKING_QRCODE_TRADE_PAY("qrcodeTradePay","多渠道下单接口"),
    PARKING_QRCODE_QUERY_TRADE("queryAtmResult","多渠道查询交易接口"),
    PR_PosTong_YShang_CODE_SERVCIE("yshangpostong","银商pos通系统接入名称"),
    PARKING_PosTong_YShang_ORDER_PAYS_SERVICE("postongorderpays","银商被扫下单接口"),
    PARKING_PosTong_YShang_QUERY_ORDERS_SERVICE("postongqueryorderstatus","银商被扫下单状态查询接口"),
    PARKING_PosTong_YShang_REVOCATION_ORDERS_SERVICE("postongrevokeorderpays","银商渠道被扫撤销交易接口"),
    PARKING_PosTong_YShang_REFUND_ORDER_PAYS_SERVICE("postongrefundorders","银商渠道被扫申请退款接口"),
    PARKING_PosTong_YShang_REVERSE_ORDERS_SERVICE("postongreverseorders","银商渠道查询订单支付冲正"),
    PosTong_YShang_CurrencyCode("156","交易币种"),
    PosTong_YShang_PayMode("CODE_SCAN","支付方式-扫码"),
    PosTong_YShang_BECODE_PAY_RESUTLT("00","成功"),
    PR_HIPPO_BECODE_ORDER_PAYS_SERVICE("hippobecode","河马付系统接入名称"),
    PARKING_HIPPO_BECODE_ORDER_PAYS_SERVICE("HippoBeCodeOrderPays","河马付刷卡下单接口"),
    PARKING_HIPPO_BECODE_QUERY_ORDERS_SERVICE("HippoQueryOrderPays","河马付被扫下单状态查询接口"),
    PARKING_HIPPO_BECODE_REVOCATION_ORDERS_SERVICE("HippoRevokeOrderPays","河马付渠道被扫撤销交易接口"),
    PARKING_HIPPO_BECODE_REFUND_ORDER_PAYS_SERVICE("HippoRefundeOrderPays","河马付渠道被扫申请退款接口"),
    PARKING_HIPPO_BECODE_QUERY_REFUND_ORDERS_SERVICE("HippoQueryRefundOrders","河马付渠道查询订单支付冲正"),
    PR_FUDIAN_BECODE_ORDER_PAYS_SERVICE("fudianbecode","富滇银行支付系统接入名称"),
    PARKING_FUDIAN_BECODE_ORDER_PAYS_SERVICE("FuDianBeCodeOrderPay","富滇被扫下单接口"),
    PARKING_FUDIAN_BECODE_QUERY_ORDERS_SERVICE("FuDianQueryOrderPay","富滇渠道被扫下单状态查询接口"),
    PARKING_FUDIAN_BECODE_REVOCATION_ORDERS_SERVICE("FuDianRevokeOrderPay","富滇渠道被扫撤销交易接口"),
    PARKING_FUDIAN_BECODE_REFUND_ORDER_PAYS_SERVICE("FuDianRefundOrderpay","富滇渠道被扫申请退款接口"),
    PR_CIB_BECODE_ORDER_PAYS_SERVICE("cibbecode","兴业银行支付系统接入名称"),
    PARKING_CIB_BECODE_ORDER_PAYS_SERVICE("cibBarCodeOrderPay","兴业银行 订单支付接口"),
    PARKING_CIB_BECODE_QUERY_ORDERS_SERVICE("cibOrderStatusPay","兴业银行 订单查询接口"),
    EPARKING_GET_PRE_PAID_AMOUNT("paidFee","车易泊预缴费返回参数说明，已支付金额，预支付"),
    CMB_DISCOUNT_INFO_UNIT("unit","招行优惠类型参数"),
    CMB_DISCOUNT_INFO_UNIT_0("0","招行优惠参数上送:优惠金额单为分"),
    CMB_DISCOUNT_INFO_UNIT_1("1","招行优惠参数上送：优惠小时单位为秒"),
    CMB_DISCOUNT_INFO_NAME("name","优惠名称"),
    CMB_DISCOUNT_INFO_NAME_AMOUNT("0","减免金额优惠"),
    CMB_DISCOUNT_INFO_NAME_SECOND("1","小时优惠"),
    CMB_DISCOUNT_INFO_VALUE("value","招行优惠费用参数：unit为0时，单位为分，unit为1时 单位为秒"),
    CALL_PAY_NOTIFY_INSIDE_ERROR("error","支付通知处理异常"),
    PR_PARKING_CMB_PAY_SERVICE("PrParkingCmbPayService","调用招行渠道系统服务名称"),
    PARKING_CMB_GET_ORDER_SERVICE("cmbGetOrder","招行内部接口查询预缴费接口名称"),
    PARKING_CMB_GET_APPID_SIGN_KEY_SERVICE("cmbGetAppIdSignKkey","招行内部接口查询私钥接口名称"),
    PARKING_CMB_PAY_NOTIFY_SERVICE("cmbPayNotify","招行支付通知"),
    PARKING_CMB_REFUND__NOTIFY_SERVICE("cmbRefundNotify","招行退款通知"),
    PARKING_CMB_AUTO_APY_BIND_SERVICE("cmbAutoPayBind","招行调用停车系统无感支付配置绑定服务接口名称"),
    PARKING_CMB_AUTO_PAY_UN_BIND_SERVICE("cmbAutoPayUnbind","招行调用停车系统无感支付配置解绑服务接口名称"),
    PARKING_CMB_PUSH_AUTO_PAY_SERVICE("cmbPushAutoPay","调用招行推送无感扣费接口服务名称"),
    PARKING_CMB_PUSH_SPACE_INFO_SERVICE("cmbPushSpaceInfo","调用招行渠道上送车位信息上报接口服务名称"),
    PARKING_CMB_PUSH_NOTIFY_INDATE_SERVICE("cmbPushNotifyIndata","调用招行渠道接入车辆入场通知服务接口名称"),
    PARKING_CMB_PUSH_NOTIFY_OUTDATE_SERVICE("cmbPushNotifyOutdata","调用招行渠道出场通知服务接口名称"),
    PARKING_CMB_GET_AUTO_PAY_STATUS_SERVICE("cmbGetAutoPayStatus","调用招行渠道查询无感支付状态接口名称"),
    DB_SELECT_APPID_KEY("isnulll","此应用代码AppId未配置"),
    QUERY_SUCCESS_RESP_DESC("SUCCESS","查询成功"),
    QUERY_FAIL_RESP_DESC("fail","查询失败"),
    CMB_PAY_TYPE_1("1","招行渠道返回状态[微信]"),
    CMB_PAY_TYPE_2("2","招行渠道返回状态[支付宝]"),
    CMB_PAY_TYPE_3("3","招行渠道返回状态[金额优惠劵]"),
    CMB_PAY_TYPE_4("4","招行渠道返回状态[折扣抵扣]"),
    CMB_PAY_TYPE_5("5","招行渠道返回返回状态[积分抵扣]"),
    CMB_PAY_TYPE_6("6","电子通用金额劵"),
    FLAG_TRADE_ID_1("1","渠道方预缴费查询订单时，订单号是是否携带字母标示，不同渠道方要求不同[1不携带字母]"),
    CMB_ENTR_IN_CODE("01","入口编号"),
    CMB_OUT_IN_CODE("02","出口编号"),
    CMB_CAR_TYPE_1("1","小车"),
    CMB_CAR_TYPE_2("2","大车"),
    CMB_CAR_TYPE_65534("65534","军警车"),
    CMB_POWER_TYPE_1("1","普通"),
    CMB_POWER_TYPE_2("2","混合动力"),
    CMB_POWER_TYPE_3("3","纯电力"),
    CMB_BODY_COLOR_0("0","蓝色"),
    CMB_BODY_COLOR_1("1","黄色"),
    CMB_BODY_COLOR_2("2","白色"),
    CMB_BODY_COLER_3("3","黑色"),
    CMB_BODY_COLER_4("4","绿色"),
    CMB_PLATE_COLOR_0("0","蓝色"),
    CMB_PLATE_COLOR_1("1","黄色"),
    CMB_PLATE_COLOR_2("2","白色"),
    CMB_PLATE_COLER_3("3","黑色"),
    CMB_PLATE_COLER_4("4","绿色"),
    CMB_CAR_LOG("00","车标"),
    CMB_CAR_MODEL_0("0","未知"),
    CMB_CAR_MODEL_1("1","轿车"),
    CMB_CAR_MODEL_2("2","面包车"),
    CMB_CAR_MODEL_3("3","大客车"),
    CMB_CAR_MODEL_4("4","中客"),
    CMB_CAR_MODEL_5("5","皮卡"),
    CMB_CAR_MODEL_6("6","非机动车"),
    CMB_CAR_MODEL_7("7","SUV"),
    CMB_CAR_MODEL_8("8","MPV"),
    CMB_CAR_MODEL_9("9","微货"),
    CMB_CAR_MODEL_10("10","轻货"),
    CMB_CAR_MODEL_11("11","中货"),
    CMB_ENTER_INSUCCESS("InSucceed(CmbPaySon)","入场通知成功"),
    CMB_ENTER_INFAILL("InFailure(CmbPaySon)","入场通知失败"),
    CMB_OUTSUCCESS("OutSuccess(CmbPaySon)","出场通知成功"),
    CMB_OUTFAIL("OutFail(CmbPaySon)","出场通知失败"),
    PARKING_CHANNEL_CONF_DESC("9999010","此停车场未配置渠道路由,需配置"),
    PARKING_INSERT_TAG("I","DB插入标示"),
    PARKING_UPDATE_TAG("U","DB更新标示"),
    PARKING_ENTER_SUCCESS_DESC("000000","入场通知成功"),
    CMB_AUTO_TYPE("0","招行授权类型"),
    QUERY_PERMI_STATEUS_00("00","无感状态"),
    QUERY_PERMI_STATEUS_03("03","无感其他状态"),
    GZBD_QUERY_PERMIN_STATE_METHOD_NAME("queryPermitState","无感接口内部方法名称"),
    PR_CUSTER_SERVICE("CustService","客户系统自定义内部名称"),
    PR_AUTH_SERVICE("AuthService","公共系统授权自定义系统，设计到用户时用验证"),
    REFUND_TRADE_NOTIFY_FAIL_DESC("","退款通知失败"),
    PR_NOTIFY_QRCODE_PAY_RESULT_SERVICE("notifyQrCodePayResult","统一渠道被扫支付交易通知"),
    NOTIFY_CLOUD_STATUS_SUCCESS("{\"status\":\"success\"}","通知对账cloud系统状态"),
    RIGHT_MONEY("0","权益使用金额置默认值"),
    EQUITY_PICE("0","使用使用金额"),
    RIGHT_ID("0","权益id"),
    CALL_PAY_SYS_EXCEPTION_DESC("","调用支付系统异常"),
    QUERY_CHANNEL_ORDER_STARUS("queryChannelOrderStatus","主动查询各渠道订单支付状态"),
    EFFECT_TIMES("3","次数"),
    OVER_TIME("3m","超时时间3分钟"),
    MCHNT_PRE("0","置默认值折扣0"),
    PRE_DESCRIBE("0","置默认值折扣描述"),
    PAY_MODE_1("1","支付方式主被动 0:主动 1:自动"),
    PAY_MODE_0("0","支付方式主被动 0:主动 1:自动"),
    CAR_NO_REG_DESC("999910","车牌未登记"),
    PARKING_NO_CHANEL_ROUTE_REG_DESC("999910","未配置停车场支付渠道路由["),
    PARKING_NO_SERVICE("service","查无此应用接口，此参数缺失，请检查"),
    PARKING_NO_RECORD_DESC("999916","无停车记录"),
    AUTH_LOGIN_TOKEN_SERVCIE("authLoginToken","认证服务"),
    IS_NULL("null","业务参数缺失"),
    IS_NULL_PARASM("Null","参数Null"),
    USER_CHANNEL_BACK("","此车牌为黑名单用户"),
    CAR_CANCEL_0("0","车牌解绑"),
    CAR_BIND_1("1","车牌绑定"),
    UNIONPAY_PARAMS_BIND_TYPE("bind_type","绑定和解绑状态"),
    UNIONPAY_PARAMS_PARK_NAME("park_name","车场名称"),
    UNIONPAY_PARAMS_PARK_NO("park_no","停车场id"),
    UNIONPAY_PARAMS_USR_NUM("usr_num","车牌"),
    CLOUD_CAR_BIND_STATE("0","场内通知cloud白名单绑定状态"),
    CLOUD_CAR_CANCEL_STATE("1","场内通知cloud解绑状态"),
    UNION_PAY_NOTIFY("UnionPayNotify","云闪付支付通知"),
    ORDER_REQSUMIT_DESC("","此笔订单重复交易，需核实"),
    ORDER_RES_TYPE_DESC("","此业务类型不符，请核实"),
    RES_TYPE_PARKING_PRE("parkingPre","临时停车缴费类型"),
    NOTIFY_TRADE_RESULT("notifyTradeResult","交易通知,推送通知系统"),
    ORDER_NO_DESC("","无此订单,请核实"),
    ORDER_DB_EXCEPITON_DESC("","数据处理异常"),
    QUERY_CAR_IN_OUT_REORD_DESC("","未查询到入场记录"),
    REQ_OVER_TIME_ERROR_DESC("","请求超时"),
    ORDER_FAIL_DESC("","下单失败"),
    PR_FALUTl_TOLEARNT_SERVICES_SYNS("FalutlTolearantService","容错平台系统名称"),
    FALUT_TOLERANT_NOTIFY_NO_DESC("","此订单无需容错"),
    FALUT_TOLERANT_NOTIFY_SUCCESS_DESC("","此订单已容错"),
    REQ_PARAMS_QUERY_ORDER_ID("orderId","订单号属性"),
    REQ_PARAMS_APP_CODE("appCode","应用编码"),
    CHANNEL_ID_85100100("85100100","渠道号"),
    QUERY_ORDER_FAIL_DESC("","查询失败"),
    QUERY_ORDER_SUCCESS_DESC("","查询成功"),
    PRE_CHANNEL_ROUTE_CONFIG_NO_DESC("","此停车场未配置渠道路由"),
    PRE_CHANNEL_ROUTE_CONFIG_MCHN_NO_DESC("","未配置渠道商户"),
    PARKING_NO_APP_SERVICE_DESC("","查无此应用接口"),
    H5_PAY_METHO_1("1", "重定向"),
    H5_PAY_METHO_2("2","直接输出网页"),
    H5_PAY_METHO_3("3","js组装文件支付调起"),
    ICBC_CHANNEL_NUM_4("4","工行默认收单编码");
	
	private CommEnum(String rspCode,String rspMsg){
		this.rspCode=rspCode;
		this.rspMsg=rspMsg;
	}
	private String rspCode;
	private String rspMsg;
	public String getRspCode() {
		return rspCode;
	}
	public void setRspCode(String rspCode) {
		this.rspCode = rspCode;
	}
	public String getRspMsg() {
		return rspMsg;
	}
	public void setRspMsg(String rspMsg) {
		this.rspMsg = rspMsg;
	}
	
   
}

